# Generated by Django 4.2.1 on 2023-06-23 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collecteapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnees',
            name='id_capteur',
            field=models.ForeignKey(blank=True, db_column='id_capteur', null=True, on_delete=django.db.models.deletion.CASCADE, to='Collecteapp.capteur'),
        ),
    ]
