# Generated by Django 4.2.1 on 2023-06-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Collecteapp', '0002_alter_capteur_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='piece',
            field=models.CharField(max_length=255),
        ),
    ]
