# Generated by Django 4.2.1 on 2023-06-23 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Collecteapp', '0002_alter_donnees_id_capteur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capteur',
            name='piece',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donnees',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='donnees',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='donnees',
            name='id_capteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Collecteapp.capteur'),
        ),
        migrations.AlterField(
            model_name='donnees',
            name='temps',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donnees',
            name='time',
            field=models.TimeField(),
        ),
    ]
