# Generated by Django 4.1.7 on 2023-06-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('piece', models.CharField(max_length=100, verbose_name='Pièce')),
                ('date', models.DateField(verbose_name='Date')),
                ('heure', models.TimeField(verbose_name='Heure')),
                ('temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Température')),
            ],
        ),
    ]
